In [1]:
import numpy as np

In [3]:
arr=np.array([1,2,3])
arr

array([1, 2, 3])

In [5]:
list_of_lists=np.array(([1,2,3],[3,4,6],[5,6,7]))
list_of_lists

array([[1, 2, 3],
       [3, 4, 6],
       [5, 6, 7]])

In [6]:
np.arange(54,67)

array([54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66])

In [7]:
np.arange(54,67,6)

array([54, 60, 66])

In [8]:
np.zeros(3)

array([0., 0., 0.])

In [9]:
np.zeros(5,int)

array([0, 0, 0, 0, 0])

In [10]:
np.zeros((2,5),int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [13]:
np.linspace(0,1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [14]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [15]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [18]:
np.eye(5,)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [20]:
np.random.rand(2)

array([0.62690554, 0.91899241])

In [63]:
rand_arr=np.random.randint(0,10,5)
rand_arr

array([5, 5, 5, 2, 2])

In [64]:
rand_arr.min()

2

In [65]:
rand_arr.max()

5

In [25]:
rand_arr.argmin()

4

In [26]:
rand_arr.argmax()

1

In [31]:
simple_arr=np.arange(10,26)
simple_arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25])

In [62]:
simple_arr=simple_arr.reshape(3,4)

ValueError: cannot reshape array of size 16 into shape (3,4)

# Two-dimensional array

In [36]:
simple_matrix=np.array([[1,2,3,4],[2,3,4,5],[6,7,8,9],[3,4,5,6]])
simple_matrix

array([[1, 2, 3, 4],
       [2, 3, 4, 5],
       [6, 7, 8, 9],
       [3, 4, 5, 6]])

In [37]:
simple_matrix[2:3]

array([[6, 7, 8, 9]])

In [38]:
simple_matrix[:,2]

array([3, 4, 8, 5])

In [39]:
simple_matrix[1,1]

3

In [40]:
simple_matrix[1:3,2:4]

array([[4, 5],
       [8, 9]])

In [42]:
simple_matrix[1:,2:]

array([[4, 5],
       [8, 9],
       [5, 6]])

In [43]:
simple_matrix[2]

array([6, 7, 8, 9])

In [44]:
simple_matrix[:,(3,2)]

array([[4, 3],
       [5, 4],
       [9, 8],
       [6, 5]])

In [46]:
sample_array=np.arange(1,31)
sample_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [47]:
sample_array+sample_array

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60])

In [60]:
np.exp(sample_array)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04, 5.98741417e+04, 1.62754791e+05,
       4.42413392e+05, 1.20260428e+06, 3.26901737e+06, 8.88611052e+06,
       2.41549528e+07, 6.56599691e+07, 1.78482301e+08, 4.85165195e+08,
       1.31881573e+09, 3.58491285e+09, 9.74480345e+09, 2.64891221e+10,
       7.20048993e+10, 1.95729609e+11, 5.32048241e+11, 1.44625706e+12,
       3.93133430e+12, 1.06864746e+13])

In [49]:
np.log(sample_array)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509,
       2.39789527, 2.48490665, 2.56494936, 2.63905733, 2.7080502 ,
       2.77258872, 2.83321334, 2.89037176, 2.94443898, 2.99573227,
       3.04452244, 3.09104245, 3.13549422, 3.17805383, 3.21887582,
       3.25809654, 3.29583687, 3.33220451, 3.36729583, 3.40119738])

In [50]:
np.sqrt(sample_array)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766,
       3.31662479, 3.46410162, 3.60555128, 3.74165739, 3.87298335,
       4.        , 4.12310563, 4.24264069, 4.35889894, 4.47213595,
       4.58257569, 4.69041576, 4.79583152, 4.89897949, 5.        ,
       5.09901951, 5.19615242, 5.29150262, 5.38516481, 5.47722558])

In [51]:
np.max(sample_array)

30

In [52]:
np.min(sample_array)

1

In [54]:
np.argmax(sample_array)

29

In [55]:
np.argmin(sample_array)

0

In [56]:
np.std(sample_array)

8.65544144839919

In [57]:
np.var(sample_array)

74.91666666666667

In [58]:
np.mean(sample_array)

15.5

# Pandas

In [59]:
import pandas as pd

In [66]:
labls=["w",'x','y','z']
sample_list=[10,20,30,40]
array=np.array([10,20,30,40])
dict={'w':10,"x":20,"y":30,"z":40}


In [67]:
pd.Series(data=sample_list)

0    10
1    20
2    30
3    40
dtype: int64

In [68]:
pd.Series(data=sample_list,index=labls)

w    10
x    20
y    30
z    40
dtype: int64

In [69]:
pd.Series(array,labls)

w    10
x    20
y    30
z    40
dtype: int32

In [70]:
pd.Series(dict)

w    10
x    20
y    30
z    40
dtype: int64

# Pandas dataframe and indexing

In [72]:
sports1=pd.Series([1,2,3,4],index=['cricket','football','baskball','golf'])
sports1

cricket     1
football    2
baskball    3
golf        4
dtype: int64

In [73]:
sports1['golf']

4

In [76]:
sports2=pd.Series([11,2,33,4],index=['cricket','football','baseball','golf'])
sports2

cricket     11
football     2
baseball    33
golf         4
dtype: int64

In [77]:
sports1+sports2

baseball     NaN
baskball     NaN
cricket     12.0
football     4.0
golf         8.0
dtype: float64

In [79]:
df1=pd.DataFrame(np.random.randn(8,5),index="A B C D E F G H".split(),columns="Score1 Score2 Score3 Score4 Score5".split())
df1

Score1    Score2    Score3    Score4    Score5
A  0.076991 -0.619067 -0.632012  0.118664 -1.171895
B -0.430052  0.459685 -1.306457 -1.168838  1.541668
C  0.950869 -0.228141  0.142024 -0.104746 -1.924196
D  0.093967  0.530941 -1.665696 -0.155887 -0.177889
E -0.126519 -0.859936 -0.526581 -0.791539 -0.485425
F -0.163261  0.593701 -0.318123  0.800113 -0.205674
G -0.111678  0.671102  1.257831 -0.860590 -1.729263
H  0.393427  0.255425 -1.244344 -0.724786 -0.406074

In [80]:
df1["Score1"]

A    0.076991
B   -0.430052
C    0.950869
D    0.093967
E   -0.126519
F   -0.163261
G   -0.111678
H    0.393427
Name: Score1, dtype: float64

In [82]:
df1[["Score1","Score2"]]

Score1    Score2
A  0.076991 -0.619067
B -0.430052  0.459685
C  0.950869 -0.228141
D  0.093967  0.530941
E -0.126519 -0.859936
F -0.163261  0.593701
G -0.111678  0.671102
H  0.393427  0.255425

In [83]:
df1["Score6"]=df1["Score1"]+df1["Score2"]

In [84]:
df1

Score1    Score2    Score3    Score4    Score5    Score6
A  0.076991 -0.619067 -0.632012  0.118664 -1.171895 -0.542076
B -0.430052  0.459685 -1.306457 -1.168838  1.541668  0.029632
C  0.950869 -0.228141  0.142024 -0.104746 -1.924196  0.722727
D  0.093967  0.530941 -1.665696 -0.155887 -0.177889  0.624908
E -0.126519 -0.859936 -0.526581 -0.791539 -0.485425 -0.986454
F -0.163261  0.593701 -0.318123  0.800113 -0.205674  0.430440
G -0.111678  0.671102  1.257831 -0.860590 -1.729263  0.559424
H  0.393427  0.255425 -1.244344 -0.724786 -0.406074  0.648852

In [86]:
df1.drop("A")

Score1    Score2    Score3    Score4    Score5    Score6
B -0.430052  0.459685 -1.306457 -1.168838  1.541668  0.029632
C  0.950869 -0.228141  0.142024 -0.104746 -1.924196  0.722727
D  0.093967  0.530941 -1.665696 -0.155887 -0.177889  0.624908
E -0.126519 -0.859936 -0.526581 -0.791539 -0.485425 -0.986454
F -0.163261  0.593701 -0.318123  0.800113 -0.205674  0.430440
G -0.111678  0.671102  1.257831 -0.860590 -1.729263  0.559424
H  0.393427  0.255425 -1.244344 -0.724786 -0.406074  0.648852

In [87]:
df1.drop("Score1",axis=1)

Score2    Score3    Score4    Score5    Score6
A -0.619067 -0.632012  0.118664 -1.171895 -0.542076
B  0.459685 -1.306457 -1.168838  1.541668  0.029632
C -0.228141  0.142024 -0.104746 -1.924196  0.722727
D  0.530941 -1.665696 -0.155887 -0.177889  0.624908
E -0.859936 -0.526581 -0.791539 -0.485425 -0.986454
F  0.593701 -0.318123  0.800113 -0.205674  0.430440
G  0.671102  1.257831 -0.860590 -1.729263  0.559424
H  0.255425 -1.244344 -0.724786 -0.406074  0.648852

In [88]:
df=pd.read_csv('CRAN_mirrors.csv')

In [93]:
df.sample(5)

Name    Country      City  \
29       China (Nanjing) [https]      China   Nanjing   
32      China (Shenzhen) [https]      China  Shenzhen   
68         Korea (Ulsan) [https]      Korea     Ulsan   
93              USA (IA) [https]        USA      Ames   
3   Australia (Canberra) [https]  Australia  Canberra   

                                     URL  \
29      https://mirrors.nju.edu.cn/CRAN/   
32  https://mirrors.sustech.edu.cn/CRAN/   
68             https://cran.biodisk.org/   
93  https://mirror.las.iastate.edu/CRAN/   
3                 https://cran.csiro.au/   

                                                 Host  \
29                eScience Center, Nanjing University   
32  Southern University of Science and Technology ...   
68  The Genome Institute of UNIST (Ulsan National ...   
93                    Iowa State University, Ames, IA   
3                                               CSIRO   

                                           Maintainer  OK CountryCode  \
29                                  my # yaoge123.com   1          cn   
32                               cra # sustech.edu.cn   1          cn   
68                                ldsrman # gmail.com   1          kr   
93                               statit # iastate.edu   1          us   
3   ben.tan # csiro.au, Jayesh.joshi # csiro.au, C...   1          au   

                      Comment  
29  secure_mirror_from_master  
32                        NaN  
68  secure_mirror_from_master  
93  secure_mirror_from_master  
3   secure_mirror_from_master

In [94]:
df.shape

(106, 9)

In [99]:
df.columns

Index(['Name', 'Country', 'City', 'URL', 'Host', 'Maintainer', 'OK',
       'CountryCode', 'Comment'],
      dtype='object')

In [102]:
df.dtypes

Name           object
Country        object
City           object
URL            object
Host           object
Maintainer     object
OK              int64
CountryCode    object
Comment        object
dtype: object

In [103]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 106 entries, 0 to 105
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype 
---  ------       --------------  ----- 
 0   Name         106 non-null    object
 1   Country      106 non-null    object
 2   City         106 non-null    object
 3   URL          106 non-null    object
 4   Host         106 non-null    object
 5   Maintainer   106 non-null    object
 6   OK           106 non-null    int64 
 7   CountryCode  106 non-null    object
 8   Comment      78 non-null     object
dtypes: int64(1), object(8)
memory usage: 7.6+ KB


In [104]:
df.isnull().sum()

Name            0
Country         0
City            0
URL             0
Host            0
Maintainer      0
OK              0
CountryCode     0
Comment        28
dtype: int64