In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
from sklearn.svm import SVC

In [3]:
df = pd.read_csv('https://raw.githubusercontent.com/aniruddhachoudhury/Red-Wine-Quality/master/winequality-red.csv')

In [4]:
df.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.4              0.70         0.00             1.9      0.076   
1            7.8              0.88         0.00             2.6      0.098   
2            7.8              0.76         0.04             2.3      0.092   
3           11.2              0.28         0.56             1.9      0.075   
4            7.4              0.70         0.00             1.9      0.076   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 11.0                  34.0   0.9978  3.51       0.56   
1                 25.0                  67.0   0.9968  3.20       0.68   
2                 15.0                  54.0   0.9970  3.26       0.65   
3                 17.0                  60.0   0.9980  3.16       0.58   
4                 11.0                  34.0   0.9978  3.51       0.56   

   alcohol  quality  
0      9.4        5  
1      9.8        5  
2      9.8        5  
3      9.8        6  
4      9.4        5

**ML Pipline**
1) Import the data
2) EDA
3) Perform preprossing 
4) Create a Model
5) Evelute the Model


In [5]:
df.columns

Index(['fixed acidity', 'volatile acidity', 'citric acid', 'residual sugar',
       'chlorides', 'free sulfur dioxide', 'total sulfur dioxide', 'density',
       'pH', 'sulphates', 'alcohol', 'quality'],
      dtype='object')

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1599 entries, 0 to 1598
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   fixed acidity         1599 non-null   float64
 1   volatile acidity      1599 non-null   float64
 2   citric acid           1599 non-null   float64
 3   residual sugar        1599 non-null   float64
 4   chlorides             1599 non-null   float64
 5   free sulfur dioxide   1599 non-null   float64
 6   total sulfur dioxide  1599 non-null   float64
 7   density               1599 non-null   float64
 8   pH                    1599 non-null   float64
 9   sulphates             1599 non-null   float64
 10  alcohol               1599 non-null   float64
 11  quality               1599 non-null   int64  
dtypes: float64(11), int64(1)
memory usage: 150.0 KB


In [7]:
df.describe()

fixed acidity  volatile acidity  citric acid  residual sugar  \
count    1599.000000       1599.000000  1599.000000     1599.000000   
mean        8.319637          0.527821     0.270976        2.538806   
std         1.741096          0.179060     0.194801        1.409928   
min         4.600000          0.120000     0.000000        0.900000   
25%         7.100000          0.390000     0.090000        1.900000   
50%         7.900000          0.520000     0.260000        2.200000   
75%         9.200000          0.640000     0.420000        2.600000   
max        15.900000          1.580000     1.000000       15.500000   

         chlorides  free sulfur dioxide  total sulfur dioxide      density  \
count  1599.000000          1599.000000           1599.000000  1599.000000   
mean      0.087467            15.874922             46.467792     0.996747   
std       0.047065            10.460157             32.895324     0.001887   
min       0.012000             1.000000              6.000000     0.990070   
25%       0.070000             7.000000             22.000000     0.995600   
50%       0.079000            14.000000             38.000000     0.996750   
75%       0.090000            21.000000             62.000000     0.997835   
max       0.611000            72.000000            289.000000     1.003690   

                pH    sulphates      alcohol      quality  
count  1599.000000  1599.000000  1599.000000  1599.000000  
mean      3.311113     0.658149    10.422983     5.636023  
std       0.154386     0.169507     1.065668     0.807569  
min       2.740000     0.330000     8.400000     3.000000  
25%       3.210000     0.550000     9.500000     5.000000  
50%       3.310000     0.620000    10.200000     6.000000  
75%       3.400000     0.730000    11.100000     6.000000  
max       4.010000     2.000000    14.900000     8.000000

In [8]:
df.quality.value_counts()

5    681
6    638
7    199
4     53
8     18
3     10
Name: quality, dtype: int64

In [9]:
from sklearn.preprocessing import StandardScaler

In [10]:
scaler=StandardScaler()
scaler

StandardScaler()

In [11]:
X=df.drop('quality',axis=1)
y=df['quality']


In [12]:
from sklearn.model_selection import train_test_split

In [13]:
X_train,x_test,y_train,y_test = train_test_split(X,y,test_size=0.33,random_state=32)

In [14]:
X_train=scaler.fit_transform(X_train)


In [15]:
X_train

array([[ 0.53082412, -0.23235083,  0.45163772, ..., -0.25529083,
         0.74839593,  0.45272171],
       [-1.53832474,  2.14910132, -1.39848382, ...,  2.39234159,
         0.44767857,  0.92643853],
       [-0.75540355,  0.15988835, -0.73038438, ...,  0.19674397,
        -0.39433002, -1.15791546],
       ...,
       [-0.64355767,  1.70082797, -1.39848382, ...,  0.51962597,
        -0.81533432, -0.39996856],
       [-1.20278709,  0.15988835, -0.93595344, ...,  1.48827198,
        -0.33418655,  0.83169516],
       [-1.0909412 ,  0.21592251, -1.29569929, ...,  0.97166078,
         0.14696122, -0.87368537]])

In [16]:
model=SVC()
model

SVC()

In [17]:
model.fit(X_train,y_train)

SVC()

In [18]:
model.score(X_train,y_train)

0.6834733893557423

In [19]:
x_test=scaler.transform(x_test)

In [20]:
model.predict(x_test)

array([6, 7, 5, 5, 5, 6, 5, 5, 5, 7, 7, 5, 5, 6, 5, 6, 5, 6, 6, 6, 5, 5,
       6, 5, 6, 6, 5, 6, 5, 5, 6, 5, 7, 6, 5, 6, 6, 5, 6, 6, 6, 6, 6, 5,
       5, 6, 5, 6, 6, 5, 5, 5, 5, 6, 6, 6, 5, 5, 5, 7, 6, 6, 6, 5, 6, 5,
       6, 5, 5, 6, 5, 6, 6, 6, 5, 5, 6, 6, 6, 6, 6, 5, 6, 6, 6, 5, 6, 5,
       6, 5, 6, 5, 6, 6, 5, 5, 5, 6, 5, 5, 6, 5, 6, 6, 6, 6, 6, 6, 5, 6,
       6, 5, 6, 5, 5, 5, 6, 6, 6, 5, 5, 6, 5, 7, 5, 5, 5, 6, 5, 5, 5, 5,
       6, 5, 6, 5, 5, 6, 6, 5, 5, 6, 5, 6, 5, 5, 6, 6, 5, 6, 5, 5, 6, 6,
       5, 5, 5, 6, 5, 6, 5, 5, 5, 6, 5, 5, 5, 6, 6, 5, 5, 6, 6, 5, 6, 7,
       5, 5, 5, 6, 5, 7, 5, 6, 6, 5, 5, 5, 6, 6, 6, 6, 5, 6, 7, 6, 6, 6,
       6, 5, 6, 5, 6, 6, 6, 5, 5, 7, 6, 6, 6, 6, 5, 5, 5, 6, 6, 6, 5, 5,
       6, 6, 6, 6, 5, 5, 5, 6, 5, 7, 5, 5, 6, 6, 5, 7, 5, 5, 5, 5, 6, 5,
       6, 6, 5, 6, 6, 6, 5, 7, 7, 6, 6, 5, 6, 5, 6, 5, 5, 7, 7, 6, 5, 7,
       6, 5, 6, 6, 6, 6, 5, 5, 5, 5, 7, 5, 6, 5, 5, 6, 6, 5, 6, 6, 6, 5,
       5, 6, 6, 5, 6, 5, 5, 6, 5, 5, 5, 5, 5, 5, 5,

In [21]:
y_test

348     6
423     7
851     5
754     6
1260    5
       ..
1505    3
1       5
527     6
506     7
1081    7
Name: quality, Length: 528, dtype: int64

In [22]:
from sklearn.metrics import accuracy_score

In [23]:
accuracy_score(y_test,model.predict(x_test))

0.5928030303030303

In [24]:
from sklearn.linear_model import LogisticRegression

In [25]:
model_lg=LogisticRegression()
model_lg

LogisticRegression()

In [26]:
model_lg.fit(X_train,y_train)

LogisticRegression()

In [27]:
model_lg.score(X_train,y_train)

0.6293183940242764

In [28]:
model_lg.predict(x_test)

array([6, 7, 5, 5, 5, 7, 5, 5, 6, 7, 7, 5, 6, 7, 5, 6, 5, 6, 6, 6, 5, 5,
       6, 5, 6, 6, 5, 6, 5, 5, 5, 5, 7, 6, 5, 6, 6, 5, 6, 6, 6, 6, 6, 6,
       6, 6, 5, 6, 6, 6, 5, 5, 5, 6, 6, 6, 5, 6, 5, 7, 6, 7, 6, 5, 6, 5,
       6, 5, 5, 6, 5, 6, 6, 5, 5, 5, 6, 6, 6, 6, 6, 5, 6, 6, 6, 5, 6, 5,
       6, 5, 6, 5, 6, 6, 5, 5, 5, 5, 5, 5, 6, 5, 6, 7, 6, 6, 6, 6, 5, 6,
       5, 5, 6, 5, 5, 5, 6, 6, 5, 5, 5, 6, 5, 7, 5, 5, 6, 6, 6, 5, 6, 5,
       6, 5, 6, 6, 5, 6, 6, 6, 6, 6, 5, 7, 5, 5, 6, 6, 5, 6, 5, 5, 5, 6,
       5, 5, 5, 6, 5, 5, 5, 5, 6, 6, 5, 5, 5, 6, 6, 5, 6, 6, 6, 5, 6, 7,
       5, 5, 5, 6, 5, 7, 5, 7, 6, 5, 5, 5, 6, 6, 6, 5, 5, 6, 7, 6, 5, 6,
       7, 5, 6, 5, 6, 6, 6, 5, 5, 7, 6, 7, 6, 6, 5, 5, 6, 6, 6, 6, 6, 6,
       6, 6, 7, 6, 5, 6, 5, 6, 5, 6, 5, 5, 5, 5, 5, 7, 6, 5, 5, 5, 6, 5,
       6, 6, 6, 6, 6, 6, 5, 7, 7, 5, 7, 5, 6, 5, 6, 5, 5, 7, 7, 6, 5, 7,
       6, 6, 6, 6, 6, 5, 5, 5, 5, 5, 7, 5, 6, 5, 5, 6, 7, 5, 5, 7, 6, 5,
       5, 6, 6, 5, 6, 6, 6, 6, 5, 6, 6, 5, 5, 5, 5,

In [29]:
accuracy_score(y_test,model_lg.predict(x_test))

0.5587121212121212